--- #YAML:1.0
name:               Text-ParseWords
version:            3.27
abstract:           parse text into an array of tokens or array of arrays
author:
    - Alexandr Ciornii <alexchorny@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:          5.006
    Scalar::Util:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
